-- Conforme relação do SIPROQUIM da Polícia Federal

INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN404888', 'DILTIAZEM', '29349949');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN405889', 'HIDROXIZINA', '29335919');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN406890', 'LEVAMISOL', '29349953');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN407891', 'PARACETAMOL', '29242913');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN408892', 'TEOFILINA', '29395910');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN409893', 'TETRACAÍNA', '29224990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN410894', 'TETRAMISOL', '29349952');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN411895', 'CIANOBOROHIDRETO DE SÓDIO', '28372011');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN412896', 'DIÓXIDO DE MANGANÊS', '28201000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN413897', 'METABISSULFITO DE SÓDIO', '28321090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN414898', 'ÓXIDO DE MANGANÊS', '28200000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12441028', 'ÓXIDO DE CÁLCIO, OUTROS', '28259090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12451029', 'PENTACLORETO DE FÓSFORO', '28121400');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12461030', 'PERMANGANATO DE POTÁSSIO', '28416100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12471031', 'PERÓXIDO DE HIDROGÊNIO', '28470000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12481032', 'PIPERIDINA E SEUS SAIS', '29333200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12491033', 'PIPERONAL', '29329300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12501034', 'PIRIDINA', '29333110');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12511034', 'PIRIDINA, SAIS', '29333120');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12521036', 'PROCAÍNA E SEUS SAIS', '29224990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12531037', 'PROPIOFENONA', '29143990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12541038', 'PSEUDOEFEDRINA E SEUS SAIS', '29394200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12551039', 'QUEROSENE (DE AVIAÇÃO)', '27101911');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12561039', 'QUEROSENE, OUTROS', '27101919');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12571041', 'SAFROL', '29329400');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12591043', 'SULFATO DE SÓDIO ANIDRO', '28331110');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12611045', 'TETRACLOROETILENO', '29032300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12621046', 'TETRAHIDROFURANO', '29321100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12641048', 'TOLUENO (OUTROS)', '29023000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12651048', 'TOLUENO (TOLUOL)', '27072000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12661050', 'TRICLOROETILENO', '29032200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12671051', 'URÉIA (TEOR DE N > 45%, EM PESO)', '31021010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12681051', 'URÉIA, OUTRAS', '31021090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12691053', 'XILENOS (MISTURA DE ISÔMEROS DO XILENO)', '29024400');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12701053', 'XILENOS (M-XILENO)', '29024200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12711053', 'XILENOS (O-XILENO)', '29024100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12721053', 'XILENOS (P-XILENO)', '29024300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12731053', 'XILENOS (XILOL)', '27073000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12741053', 'XILENOS, OUTROS', '29029090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12761055', '1,2-DICLOROETANO', '29031500');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12771056', '1-FENIL-2-PROPANONA', '29143100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12791058', '3,4-METILENODIOXIFENIL-2-PROPANONA', '29329200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12811060', 'ACETATO DE ETILA ', '29153100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12821061', 'ACETATO DE ISOAMILA', '29153939');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12831062', 'ACETATO DE ISOBUTILA', '29153939');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12841063', 'ACETATO DE ISOPROPILA', '29153939');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12851064', 'ACETATO DE n-BUTILA ', '29153300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12861065', 'ACETATO DE n-PROPILA ', '29153931');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12871066', 'ACETATO DE sec-BUTILA', '29153939');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12881067', 'ACETONA', '29141100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12901069', 'ÁCIDO ACÉTICO ', '29152100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12911070', 'ÁCIDO ANTRANÍLICO E SEUS SAIS', '29224300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12921071', 'ÁCIDO BENZÓICO ', '29163110');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12931072', 'ÁCIDO BÓRICO E SEUS SAIS', '28100010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12941073', 'ÁCIDO BROMÍDRICO', '28111990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12951074', 'ÁCIDO CLORÍDRICO (ESTADO GASOSO)', '28061010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12961074', 'ÁCIDO CLORÍDRICO (SOLUÇÃO AQUOSA)', '28061020');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12971076', 'ÁCIDO CLOROSSULFÔNICO', '28062000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12981077', 'ÁCIDO FENILACÉTICO, SEUS SAIS E ÉSTERES', '29163400');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN12991078', 'ÁCIDO FÓRMICO ', '29151100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13001079', 'ÁCIDO HIPOFOSFOROSO', '28111990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13011080', 'ÁCIDO IODÍDRICO', '28111990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13021081', 'ÁCIDO LISÉRGICO E SEUS SAIS', '29396300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13031082', 'ÁCIDO N-ACETILANTRANÍLICO E SEUS SAIS', '29242300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13041083', 'ÁCIDO ORTOFOSFÓRICO (teor de Fe < 750 ppm)', '28092011');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13051083', 'ÁCIDO ORTOFOSFÓRICO, OUTROS', '28092019');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13061084', 'ÁCIDO SULFÚRICO', '28070010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13071084', 'ÁCIDO SULFÚRICO FUMEGANTE', '28070020');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13081085', 'AGUARRÁS MINERAL (WHITE SPIRIT E QUALQUER PRODUTO SIMILAR)', '27101230');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13091085', 'NAFTAS PARA PETROQUÍMICA', '27101241');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13101085', 'AGUARRÁS MINERAL, OUTRAS', '27101249');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13111086', 'ÁLCOOL ETÍLICO (TEOR DE H2O <= 1% Vol)', '22071010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13121086', 'ÁLCOOL ETÍLICO (OUTROS)', '22071090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13131087', 'ÁLCOOL ISOBUTÍLICO ', '29051410');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13141088', 'ÁLCOOL ISOPROPÍLICO', '29051220');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13151089', 'ÁLCOOL METÍLICO', '29051100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13161090', 'ÁLCOOL N-BUTÍLICO', '29051300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13171091', 'ÁLCOOL N-PROPÍLICO', '29051210');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13181092', 'ÁLCOOL SEC-BUTÍLICO ', '29051420');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13201094', 'AMINOPIRINA E SEUS SAIS', '29333999');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13211095', 'AMÔNIA (GÁS - AMONÍACO ANIDRO)', '28141000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13221096', 'ANIDRIDO ACÉTICO', '29152400');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13241098', 'ANIDRIDO ISATÓICO ', '29349914');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13251099', 'ANIDRIDO PROPIÔNICO', '29159090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13261100', 'BENZALDEÍDO', '29122100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13271101', 'BENZENO (OUTROS)', '29022000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13281101', 'BENZENO (BENZOL)', '27071000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13291102', 'BENZOCAÍNA E SEUS SAIS', '29224990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13301103', 'BICARBONATO DE POTÁSSIO', '28364000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13311104', 'BICARBONATO DE SÓDIO', '28363000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13321105', 'BOROHIDRETO DE SÓDIO', '28500090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13331106', 'BROMOBENZENO', '29039921');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13341107', 'BUTILAMINA E SEUS SAIS', '29211939');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13351108', 'CAFEÍNA', '29393010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13361108', 'CAFEÍNA, SAIS', '29393020');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13371109', 'CARBONATO DE CÁLCIO', '28365000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13381110', 'CARBONATO DE POTÁSSIO', '28364000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13391111', 'CARBONATO DE SÓDIO ANIDRO', '28362010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13401111', 'CARBONATO DISSÓDICO (OUTROS)', '28362090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13411113', 'CARVÃO ATIVADO', '38021000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13421114', 'CIANETO DE BENZILA', '29269099');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13431115', 'CIANETO DE BROMOBENZILA', '29269099');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13441116', 'CICLOEXANO', '29021100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13451117', 'CICLOEXANONA', '29142210');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13461118', 'CIMENTO PORTLAND OU DO TIPO PORTLAND (CIMENTO COMUM)', '25232910');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13471118', 'CIMENTO PORTLAND OU DO TIPO PORTLAND, OUTROS', '25232990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13481119', 'CLORETO DE ACETILA', '29159090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13491120', 'CLORETO DE ALUMÍNIO', '28273200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13501121', 'CLORETO DE AMÔNIO', '28271000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13511122', 'CLORETO DE BENZILA', '29039911');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13531124', 'CLORETO DE CÁLCIO ANIDRO', '28272010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13541124', 'CLORETO DE CÁLCIO (OUTROS)', '28272090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13551125', 'CLORETO DE ETILA', '29031120');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13561126', 'CLORETO DE METILENO', '29031200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13581128', 'CLORETO DE MERCÚRIO', '28273999');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13591129', 'CLOROFÓRMIO', '29031300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13601130', 'CROMATO DE POTÁSSIO', '28415012');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13621132', 'DIACETONA ÁLCOOL', '29144010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13631133', 'DICROMATO DE POTÁSSIO', '28415014');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13641134', 'DICROMATO DE SÓDIO', '28413000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13651135', 'DIETILAMINA (ETANSILATO E OUTROS)', '29211919');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13661135', 'DIETILAMINA E SEUS SAIS', '29211915');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13671136', 'DIPIRONA', '29331111');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13681136', 'DIPIRONA (Magnopirol, Dipirona Magnésica)', '29331112');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13691136', 'DIPIRONA SODICA (OUTS.AC.1-FENIL-2,3-DIMETIL-5-PIRAZOLONA,ETC)', '29331119');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13711138', 'EFEDRINA E SEUS SAIS', '29394100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13721139', 'ERGOMETRINA E SEUS SAIS', '29396100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13731140', 'ERGOTAMINA E SEUS SAIS', '29396200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13741141', 'ETAEFEDRINA E SEUS SAIS', '29394900');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13751142', 'ÉTER DE PETRÓLEO', '27101290');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13761143', 'ÉTER ETÍLICO', '29091100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13771144', 'ETILAMINA E SEUS SAIS', '29211911');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13781145', 'FENACETINA', '29242919');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13791146', 'FENILETANOLAMINA E SEUS SAIS', '29221999');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13801147', 'FORMAMIDA', '29241929');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13811148', 'FORMIATO DE AMÔNIO', '29151290');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13821149', 'FÓSFORO VERMELHO', '28047020');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13831150', 'GAMA-BUTIROLACTONA (GBL) (outras lactonas)', '29322000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13841151', 'GASOLINA DE AVIAÇÃO', '27101251');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13851151', 'GASOLINA (outras)', '27101259');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13861152', 'HIDRETO DE ALUMÍNIO E LÍTIO', '28500090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13871153', 'HIDRÓXIDO DE AMÔNIO (AMONÍACO EM SOLUÇÃO AQUOSA)', '28142000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13881154', 'HIDRÓXIDO DE CÁLCIO (CAL APAGADA)', '25222000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13891154', 'HIDRÓXIDO DE CÁLCIO, OUTROS', '28259090');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13901155', 'HIDRÓXIDO DE POTÁSSIO', '28152000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13911156', 'HIDRÓXIDO DE SÓDIO (EM SOLUÇÃO AQUOSA)', '28151200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13921156', 'HIDRÓXIDO DE SÓDIO (SÓLIDO)', '28151100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13931157', 'HIDROXILAMINA E SEUS SAIS', '28251020');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13941158', 'HIPOCLORITO DE SÓDIO', '28289011');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13951159', 'IODO (SUBLIMADO)', '28012010');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13961160', 'ISOSAFROL', '29329100');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN13971161', 'LIDOCAÍNA E SEUS SAIS', '29242914');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14041164', 'MANITOL', '29054300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14051165', 'METILAMINA', '29211111');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14061165', 'METILAMINA, SAIS', '29211112');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14071166', 'METILERGOMETRINA, E SEUS SAIS (OUTROS)', '29396919');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14081166', 'METILERGOMETRINA, MALEATO', '29396911');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14091167', 'METILETILCETONA', '29141200');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14101168', 'METILISOBUTILCETONA', '29141300');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14111169', 'N-HEPTANO (OUTROS)', '29011000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14121169', 'N-HEPTANO COMERCIAL', '27101290');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14131170', 'N-HEXANO (OUTROS)', '29011000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14141170', 'N-HEXANO COMERCIAL', '27101210');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14151171', 'NITROETANO', '29042070');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14161172', 'N-METILEFEDRINA, SEUS SAIS E ÉSTERES', '29394900');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14171173', 'N-METILFORMAMIDA', '29241921');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14181174', 'N-METILPSEUDOEFEDRINA, SEUS SAIS E ÉSTERES', '29394900');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14191175', 'ÓLEO DE SASSAFRÁS e outros CONTENDO SAFROL', '33012990');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14201176', 'ÓLEO DIESEL', '27101921');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN14221028', 'ÓXIDO DE CÁLCIO (CAL VIVA)', '25221000');
INSERT INTO PRODUTO (codprodutoncm, descricao, codncm) VALUES ('TPN11128', 'CLORETO DE MERCÚRIO II', '28521014');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0010', 'Acessório de arma');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0020', 'Acessório explosivo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0030', 'Acessório iniciador');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0040', 'Acetileneto de prata');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0050', 'Acetileneto de cobre');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0060', 'Ácido benzílico (ácido-alfa-hidroxi-alfa-fenilbenzenoacético)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0070', 'Ácido 2,2-difenil-2-hidroxiacético');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0080', 'Ácido fluorídrico (fluoreto de hidrogênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0090', 'ácido metilfosfônico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0100', 'ácido nítrico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0110', 'acido perclórico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0120', 'acido picrâmico (dinitroaminofenol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0130', 'acido pícrico (trinitrofenol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0140', 'acroleína (aldeido acrílico; 2-propenal)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0150', 'agente de guerra química (agente químico de guerra)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0160', 'alcool 2-cloroetílico (2-cloroetanol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0170', 'alquil [metil, etil, propil (n ou iso)] fosfonofluoridratos de o-alquila (≤c10)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0180', 'alcool pinacolílico (3,3-dimetil-2-butanol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0190', 'alumínio em pó lamelar e suas ligas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0200', 'Aminofenol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0210', 'amiton: fosforotiolato de 0,0-dietil s2[(dietilamino) etil] e sais alquilados ou protonados correspondentes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0220', 'arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0230', 'arma de fogo automática');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0240', 'arma de fogo de repetição de uso permitido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0250', 'arma de fogo de repetição de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0260', 'arma de fogo para uso industrial');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0270', 'arma de fogo semi-automática de uso permitido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0280', 'arma de fogo semi-automática de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0290', 'arma de pressão por ação de gás comprimido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0300', 'arma de pressão por ação de mola (ar comprimido)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0310', 'arma de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0320', 'arma especial para dar partida em competição esportiva');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0330', 'arma especial para sinalização pirotécnica ou para salvatagem');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0340', 'armamento pesado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0350', 'armamento químico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0360', 'artefato para iniciação ou detonação de cabeça de guerra de míssil ou foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0370', 'artifício pirotécnico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0380', 'azida de chumbo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0390', 'azida de sódio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0400', 'baioneta');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0410', 'benzilato de metila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0420', 'benzilato de 3-quinuclidinila (BZ)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0430', 'bifluoreto de amônio (hidrogeno fluoreto de amônio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0440', 'bifluoreto de potássio (hidrogeno fluoreto de potássio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0450', 'bifluoreto de sódio (hidrogeno fluoreto de sódio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0460', 'blindagem balística');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0470', 'bomba explosiva');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0480', 'bomba para guerra química');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0490', 'brometo de benzila (alfa-bromotolueno; ciclita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0500', 'brometo de cianogênio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0510', 'brometo de nitrosila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0520', 'brometo de xilila (bromoxileno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0530', 'bromoacetato de etila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0540', 'bromoacetato de metila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0550', 'bromoacetona');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0560', 'bromometiletilcetona');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0570', 'butil-ferroceno (n-butil-ferroceno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0580', 'butiltetril (2,4,6-trinitrofenil-n-butilnitramina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0590', 'cabeça de guerra de míssil ou foguete, mesmo inerte ou de treinamento');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0600', 'capacete a prova de balas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0610', 'carboranos e seus derivados');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0620', 'carbonato de hexaclorodimetila (carbonato de hexaclorometila; oxalato de hexaclorodimetila; trifosgênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0630', 'carga de projeção para municão de arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0640', 'carga de projeção para municão de arma de fogo leve');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0650', 'carga de projeção para munição de armamento pesado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0660', 'catoceno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0670', 'cianeto de benzila (fenilacetonitrila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0680', 'cianeto de bromobenzila (BBC; 2-bromo-alfacianotolueno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0690', 'cianeto de hidrogênio (AC; ácido cianídrico, ácido prússico; formonitrilo; gás cianídrico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0700', 'cianeto de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0710', 'cianeto de sódio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0720', 'cianoformiato de etila (cianocarbonato de etila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0730', 'cianoformiato de metila (cianocarbonato de metila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0740', 'ciclometilenotrinitramina (ciclonite; hexogeno; RDX)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0750', 'ciclotetrametilenotetranitroamina (HMX; homociclonite; octogeno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0760', 'clorato de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0770', 'cloreto de benzila ');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0780', 'cloreto de carbonila (dicloreto de carbonila; fosgênio; oxicloreto de carbono)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0790', 'cloreto de cianogênio (CK; marguinita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0800', 'cloreto de difenilestibina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0810', 'cloreto de dimetilamina ([dimethylamine HCl])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0820', 'cloreto de enxofre (monocloreto de enxofre; dicloreto de enxofre)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0830', 'cloreto de fenilcarbilamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0840', 'cloreto de nitrobenzila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0850', 'cloreto de nitrosila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0860', 'cloreto de N, N-diisopropil-beta-aminoetila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0870', 'cloreto de oxalila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0880', 'cloreto de sulfurila (ácido clorossulfúrico; bicloridrina sulfúrica; cloreto de sulfonila; oxicloreto sulfúrico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0890', 'cloreto de tiocarbonila (tiofosgênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0900', 'cloreto de tiofosforila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0910', 'cloreto de tionila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0920', 'cloreto de trietanolamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0930', 'cloreto de xilila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0940', 'cloridrina de glicol (cloridrina etilênica)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0950', 'cloroacetato de etila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0960', 'cloroacetofenona (CN)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0970', 'cloroacetona (tomita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0980', 'clorobromoacetona (martonita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('0990', 'cloroformiato de clorometila (palita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1000', 'cloroformiato de diclorometila (palita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1010', 'formiato de etila (clorocarbonato de etila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1020', 'cloroformiato de metila (clorocarbonato de metila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1030', 'cloroformiato de triclorometila (cloreto de tricloroacetila; difosgênio; super palita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1040', 'N,N-dialquil ([metil, etilm propil (n ou isopropila)] aminoetanol-2 e sais protonatos correspondentes)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1050', 'N,N-dialquil ([metil, etilm propil (n ou isopropila)] aminoetanotiol-2 e sais protonatos correspondentes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1060', 'clorossulfonato de etila (sulvinita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1070', 'clorossulfonato de metila (vilantita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1080', 'clorovinildicloroarsina (lewisita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1090', 'colete a prova de balas de uso permitido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1100', 'colete a prova de balas de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1110', 'composto aditivo potencializador de efeito de agente de guerra química, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1120', 'composto com efeito fisiológico hematóxico (tóxico do sangue), de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1130', 'composto com efeito fisiológico lacrimogêneo, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1140', 'composto com efeito fisiológico neurotóxico (tóxico dos nervos), de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1150', 'composto com efeito fisiológico paralisante, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1160', 'composto com efeito fisiológico psicoquímico, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1170', 'composto com efeito fisiológico sobre animais, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1180', 'composto com efeito fisiológico sobre o solo, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1190', 'composto com efeito fisiológico sobre vegetais, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1200', 'composto com efeito fisiológico sufocante, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1210', 'composto com efeito fisiológico vesicante, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1220', 'composto com efeito fisiológico vomitivo (esternutatório), de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1230', 'composto com efeito fumígeno, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1240', 'composto com efeito iluminativo, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1250', 'composto com efeito incendiário, de interesse militar ');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1260', 'composto precursor de (matéria prima para) agente de guerra química, de interesse militar');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1270', 'cordel detonante');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1280', 'cresilato de amônio (ecrasita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1290', 'cresilato de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1300', 'decaboranos e seus derivados');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1310', 'detonador (espoleta) elétrico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1320', 'detonador (espoleta) de qualquer tipo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1330', 'detonador (espoleta) não elétrico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1340', 'N,N-diaquil [metil, etil, propil (n ou iso)] fosforamidocianidratos de O-alquila (<=C10, inclui cicloalquila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1350', 'S-2 diaquil [metil, etil, propil (n ou iso)] aminoetilalquil [metil, etil, propil (n ou iso)] fosfonotiolatos de O-alquila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1360', 'O-2-dialquil [metil, etil, propil (n ou iso)] aminoetilalquil, ou fosfonitos de O-alquila (H ou ≤ C10, inclusive a cicloalquila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1370', 'diazodinitrofenol (DDNP)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1380', 'diazometano (azimetileno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1390', 'dicloreto de enxofre');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1400', 'dicloreto de etilfosfonila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1410', 'dicloreto de metilfosfonila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1420', 'dicloreto etilfosfonoso (dicloreto do ácido etil fosfonoso [ethylphosphonous dicloride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1430', 'dicloreto metilfosfonoso (dicloreto do ácido metilfosfonoso [methylphosphonous dicloride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1440', 'diclorodinitrometano');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1450', '2, 2 dicloro-dietil-metilamina (HN-2)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1460', 'dicloroformoxima (CX; fosgênio oxima)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1470', '2, 2 dicloro-trietilamina (HN-1)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1480', 'dietilaminoetanol (N, N-dietiletanolamina; 2-dietilaminoetanol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1490', 'difenilaminacloroarsina (adamsita; cloreto de fenarsazina; DM)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1500', 'difenilbromoarsina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1510', 'difenilcianoarsina (cianeto de difenilarsina;Clark I; Clark II; DC)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1520', 'difenilcloroarsina (DA; cloreto de difenilarsina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1530', 'difluoreto de etilfosfonila (difluoreto do ácido etilfosfônico [ethyphosphonyl difluoride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1540', 'difluoreto de metilfosfonila ([methyphosphonyl difluoride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1550', 'difluoreto etilfosfonoso (difluoreto do ácido etilfosfonoso [ethylphosphonous difluoride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1560', 'difluoreto metilfosfonoso (difluoreto do ácido metilfosfonoso [methylphosphonous difluoride])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1570', 'diisocianato de isoforona ([isophorone diisocyanate])');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1580', 'diisopropilamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1590', 'diisopropilaminoetanotiol (N, Ndiisopropilaminoetanotiol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1600', 'diisopropil - (beta) - aminoetanol (N, Ndiisopropil - (beta) - aminoetanol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1610', 'Dimetilamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1620', 'dimetil fosforoamidato de dietila (N, Ndimetilfosforoamidato de dietila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1630', 'dimetil hidrazina assimétrica');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1640', 'dimetilnitrobenzeno (nitroxileno)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1650', 'dinamite');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1660', 'dinitrato de dietilenoglicol (DEGN)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1670', 'dinitrato de trietilenoglicol (TEGN)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1680', 'dinitrobenzeno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1690', 'dinitroglicol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1700', 'dinitrotolueno (dinitrotoluol, DNT)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1710', 'dióxido de nitrogênio (monômero do tetraóxido de dinitrogênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1720', 'dioxina (tetraclorodibenzeno-p-dioxina-2-3-7-8)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1730', 'dispositivo gerador de gás instantâneo com explosivos ou mistura pirotécnica em sua composição');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1740', 'dispositivo para acionamento de minas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1750', 'dispositivo para lançamento de gás agressivo (tubo de gás paralisante)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1760', 'dispositivo para sinalização pirotécnica ou salvatagem');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1770', 'escudo a prova de balas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1780', 'equipamento especialmente projetado para controle de tiro de artilharia, foguetes ou mísseis');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1790', 'equipamento especialmente projetado para lançamento de foguetes ou mísseis');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1800', 'equipamento (máquina) especialmente projetado para produção de agente químico de guerra');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1810', 'equipameto (máquina) especialmente projetado para produção de armas e munições');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1820', 'equipamento (máquina) especialmente projetado para produção de explosivos');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1830', 'equipamento especialmente projetado para transporte e lançamento de foguetes ou mísseis');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1840', 'equipamento para detecção de minas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1850', 'equipamento para lançamento de minas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1860', 'equipamento para recarga de munições e suas matrizes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1870', 'equipamento para visão noturna (luneta; óculos; etc)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1880', 'espada ou espadim de uso exclusivo das Forças Armadas ou Forças Auxiliares');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1890', 'espargidor de agente de guerra química');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1900', 'espoleta elétrica');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1910', 'espoleta (cápsula) para cartucho de arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1920', 'espoleta para munição explosiva');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1930', 'espoleta pirotécnica (espoleta comum)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1940', 'estágio individual para míssil ou foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1950', 'estifinato de chumbo (trinitrorresorcinato de chumbo)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1960', 'estojo (cartucho vazio) para munição de arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1970', 'estopilha (cápsula; espoleta) para carga de projeção de armamento pesado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1980', 'estopim de qualquer tipo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('1990', 'éter dibromometílico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2000', 'éter diclorometílico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2010', 'etilcarbazol (N-etilcarbazol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2020', 'Etildibromoarsina (dibromoetilarsina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2030', 'etildicloroarsina (dicloroetilarsina; ED)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2040', 'Etildietanolamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2050', 'Etilenodiaminodinitrato (etilenodinitroamina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2060', 'etilfosfonato de dietila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2070', 'etilfosfonato de dimetila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2080', 'etil-S-2-diisopropilaminoetilmetilfosfonotiolato (VX)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2090', 'explosivos não listados nesta relação');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2100', 'explosivo plástico');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2110', 'Fenildibromoarsina (dibromofenilarsina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2120', 'Fenildicloroarsina (diclorofenilarsina; PD)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2130', 'fluoreto de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2140', 'fluoreto de sódio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2150', 'fluorfenoxiaetato de clorobutila (4-fluorfenoxiacetato de 2-clorobutila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2160', 'fogos de artifício');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2170', 'foguete anti-granizo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2180', 'foguete de qualquer tipo, suas partes e componentes (material bélico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2190', 'fosfito de dietila (dietilester do ácido fosforoso, dietil fosfito; fosfito dietílico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2200', 'fosfito de dimetila (dimetil fosfito; fosfito dimetílico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2210', 'fosfito de trietila (fosfito trietílico; trietil fosfito)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2220', 'fosfito de trimetila (fosfito trimetílico; trimetil fosfito)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2230', 'fosfonildifluoretos de alquila [metil, etil, propil (n ou iso)]');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2240', 'fósforo branco ou amarelo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2250', 'fulminato de mercúrio (cianato mercúrico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2260', 'glicidil azida polimerizada');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2270', 'granada de exercício e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2280', 'granada de manejo e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2290', 'granada explosiva e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2300', 'granada perfurante e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2310', 'granada química e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2320', 'grão moldado (propelente) para foguete ou missil');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2330', 'hexanitroazobenzeno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2340', 'hexanitrocarbanilida');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2350', 'hexanitrodifenilamina (hexil)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2360', 'hexanitrodifenilsulfeto');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2370', 'hidrazina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2380', 'Hidroximetilpiperidina (3-hidroxi-1-metilpiperidina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2390', 'iodeto de benzila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2400', 'iodeto de cianogênio (cianeto de iodo)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2410', 'iodeto de fenarsazina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2420', 'iodeto de fenilarsina (iodeto de difenilarsina; iodeto de fenarsina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2430', 'iodeto de nitrobenzila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2440', 'iodoacetato de etila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2450', 'iodoacetona');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2460', 'isopurpurato de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2470', 'lança-chamas (material bélico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2480', 'lançador de bombas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2490', 'lançador de granadas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2500', 'lançador de mísseis e foguetes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2510', 'lança-rojões (material bélico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2520', 'lewisita 1: 2-clorovinildicloroarsina lewisita 2: bis (2-clorovinil) cloroarsina lewisita 3: tris (2-clorovinil) arsina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2530', 'luneta para armas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2540', 'magnésio e suas ligas, em pó');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2550', 'máscara contra gases');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2560', 'material bélico não listado nesta relação');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2570', 'material para sinalização pirotécnica e salvatagem');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2580', 'metais pulverizados, misturados a percloratos, cloratos ou cromatos');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2590', 'metais pulverizados, misturados a substâncias utilizadas como propelentes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2600', 'metildicloroarsina (diclorometilarsina; MD)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2610', 'metildietanolamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2620', 'metilfosfonato de dimetila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2630', 'metilfosfonato de 0-etil-2-diisopropilaminoetilo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2640', 'metilfosfonito de dietila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2650', 'metilidrazina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2660', 'mina explosiva e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2670', 'mira optrônica');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2680', 'míssil de qualquer tipo, suas partes e componentes (material bélico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2690', 'misturas poliméricas compostas de ácido acrílico-polibutadieno-acrilonitrila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2700', 'misturas poliméricas compostas de ácido acrílico e polibutadieno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2710', 'mostardas de enxofre, gás-mostarda, sesquimostarda, éter mostarda');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2720', 'Motores para foguetes ou mísseis de qualquer tipo ou modelo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2730', 'Munição de exercício e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2740', 'Munição de manejo e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2750', 'Munição (cartucho) de uso permitido para arma de fogo e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2760', 'Munição (cartucho) de uso restrito para arma de fogo e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2770', 'Munição (cartucho; foguete; rojão; tiro) p/ armamento pesado (canhão; lança foguete; lança granada; lança rojão; morteiro; obuseiro) e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2780', 'Munição (cartucho) para arma de uso industrial e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2790', 'Munição química e suas partes');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2800', 'mira laser');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2810', 'NAPALM (puro ou como gasolina gelatinizada para uso em bombas incendiárias e lançachamas)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2820', 'Nitrato de amila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2830', 'Nitrato de amônio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2840', 'Nitrato de etila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2850', 'Nitrato de mercúrio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2860', 'Nitrato de metila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2870', 'Nitrato de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2880', 'Nitroamido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2890', 'Nitrocelulose ou solução de nitrocelulose com qualquer teor de nitrogênio (algodão pólvora; colódio; pirocelulose, etc)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2900', 'Nitrodifenilamina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2910', 'Nitroglicerina (trinitrato de glicerila; trinitrato de glicerina; trinitroglicerina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2920', 'Nitroglicol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2930', 'Nitroguanidina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2940', 'nitromanita (hexanitrato de manitol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2950', 'Nitronaftaleno (mono; di; tri; tetra)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2960', 'nitropenta (nitropentaeritrita; nitropentaeritritol; PETN; tetranitrato de pentaeritritol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2970', 'Nitroxilenos');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2980', 'ortoclorobenzalmalononitrila (CS)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('2990', 'oxicloreto de fósforo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3000', 'óxido de dimetilaminoetoxicianofosfina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3010', 'óxido de metilisopropiloxiflorofosfina (GB; 1-metil-etil éster do ácido metilfosfonofluorídrico; SARIN)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3020', 'óxido de metilpinacoliloxifluorifosfina (GD; 1,2,2-trimetil-propil éster do ácido metilfosfonofluorídrico, SOMAN)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3030', 'óxido de tri (1-(2-metil) aziridinil) fosfina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3040', 'peça para arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3050', 'peça para arma de fogo automática');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3060', 'peça para arma de fogo de repetição de uso permitido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3070', 'peça para arma de fogo de repetição de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3080', 'peça para arma de fogo para uso industrial');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3090', 'peça para armamento pesado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3100', 'peça para arma de fogo semi-automática de uso permitido');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3110', 'peça para arma de fogo semi-automática de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3120', 'peça para arma de uso restrito');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3130', 'peça para arma especial para dar partida em competição esportiva');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3140', 'peça para arma especial para sinalização pirotécnica ou para salvatagem');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3150', 'peça para arma para guerra química');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3160', 'peça para equipamento de controle de tiro de arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3170', 'peça para equipamento de controle de tiro de míssil e foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3180', 'peça para veículo blindado de emprego militar (material bélico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3190', 'peça para veículo lançador de míssil ou foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3200', 'pentacloreto de fósforo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3210', 'PFIB: 1,1,3,3,3-pentafluoro-2-(trifluormetil) - propeno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3220', 'pentassulfeto de fósforo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3230', 'pentóxido de dinitrogênio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3240', 'perclorato de amônio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3250', 'perclorato de potássio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3260', 'peróxido de cloro');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3270', 'picrato de amônio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3280', 'pimenta líquida (gás pimenta; oleoresin capsicum (capsaicinoides): capsaicina; diidrocapsaicina; e nordiidrocapsaicina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3290', 'pinacolona (3,3-dicloro-2-butanona)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3300', 'polibutadieno carboxiterminado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3310', 'polibutadieno hidroxiterminado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3320', 'pólvoras mecânicas (branca; chocolate; negra)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3330', 'pólvoras químicas de qualquer tipo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3340', 'projetil para munição para arma de fogo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3350', 'propelentes composite');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3360', 'quinuclidinol (3-quinuclidinol; 1-azabiciclo[2,2,2] octan-3-o1)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3370', 'quinuclidinona (3- quinuclidinona)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3380', 'reforçadores (detonadores)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3390', 'Ricina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3400', 'rojão, suas partes e componentes (munição para lança-rojão)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3410', 'Saxitoxina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3420', 'silicieto de hidrogênio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3430', 'simulacro de arma de guerra.');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3440', 'substâncias químicas que contenham um átomo de fósforo ao qual estiver ligado um grupo metila, etila ou propila (n ou isopropila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3450', 'Sulfato de dimetila (sulfato de metila)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3460', 'Sulfeto de 1, 2-bis (2-cloroetiltio) etano (Q; sesquimostarda)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3470', 'Sulfeto de nitrogênio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3480', 'sulfetos de sódio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3490', 'sulfeto diclorodietílico (gás mostarda; HD; iperita; sulf de diclorodietila; sulf de dicloroetila; sulf de etila diclorado; sulf dicloroetílico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3500', 'tecido a prova de balas');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3510', 'tepan (reação de tetraetilenopentamina e acrilonitrila; HX879)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3520', 'tepanol (reação de tetraetilenopentamina, acrilonitrila e glicidol; HX878)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3530', 'tetracloreto de titânio (cloreto de titânio, fumegerita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3540', 'tetraclorodinitroetano');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3550', 'tetranitroanilina');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3560', 'tetranitrocarbasol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3570', 'tetranitrometano');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3580', 'tetranitrometilanilina (tetril)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3590', 'tetraóxido de dinitrogênio (dímero do dióxido e nitrogênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3600', 'tetrazeno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3610', 'tiodiglicol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3620', 'tricloreto de arsênio');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3630', 'tricloreto de fósforo');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3640', 'tricloreto de nitrogênio (cloreto de nitrogênio)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3650', '2, 2, 2- tricloro-trietilamina (HN-3)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3660', 'tricloronitrometano (aquinita; cloropicrina; nitrotriclorometano)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3670', 'trietanolamina (tri(2-hidroxietil) amina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3680', 'triidreto de arsênio (arsina; SA)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3690', 'trinitrato de 1,2,4-butanotriol');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3700', 'trinitrato de trimetiloletano (TMEN; trinitrato de pentaglicerina)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3710', 'Trinitroacetonitrila');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3720', 'trinitroanilina (picramida)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3730', 'trinitroanisol (eter metil-2,4,6-trinitrofenílico)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3740', 'trinitrobenzeno');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3750', 'trinitroclorometano');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3760', 'trinitrometacresol (2,4,6-trinitrometacresol, cresilita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3770', 'trinitronaftaleno (naftita)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3780', 'trinitroresorcina (ácido estifínico; 2,4,6-trinitrorresorcinol)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3790', 'trinitrotolueno (TNT)');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3800', 'veículo blindado de emprego civil');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3810', 'veículo (viatura) blindado de emprego militar, com ou sem armamento');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3820', 'veículo especial para transporte de munição, míssil ou foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3830', 'veículo (carro) de passeio blindado');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3840', 'veículo projetado ou adaptado para lançamento de míssil ou foguete');
INSERT INTO PRODUTO (codprodutoncm, descricao) VALUES ('3850', 'verniz');